- lib/screens/home.dart
This is part of the solution for #3 .
> Replace marker icons withs circles (WIP)

- lib/api/stop_query_handler.dart
- lib/screens/home.dart
- lib/widgets/loading_indicator.dart
This adds a simple circular progress indicator to the map whenever stops are loaded from the server.
> Loading stops indicator

- lib/commons/themes.dart
- lib/screens/home.dart
- lib/widgets/home_sidebar.dart
- pubspec.lock
- pubspec.yaml
> Upgrade code base to Flutter 2.5

- lib/commons/screens.dart
- lib/main.dart
- lib/models/routes.dart
- lib/screens/about.dart
- lib/screens/onboarding.dart
- lib/widgets/home_sidebar.dart
> Convert to named routes

- lib/screens/home.dart
- lib/widgets/question_inputs/number_input.dart
> Disallow comma when zero decimal places and improve error message

- ios/Podfile.lock
- lib/helpers/system_ui_adaptor.dart
- lib/main.dart
- lib/screens/onboarding.dart
Fixes #1 
Good images still missing.
> Redesign onboarding screen

- lib/screens/home.dart
- lib/view_models/preferences_provider.dart
- lib/widgets/map_overlay/map_overlay.dart
> Save location in preferences

- .github/workflows/tests.yml
This PR aims to fix the currently failing workflow.
At the moment it's not clear what actually causes the problem.
> Fix tests.yml

- lib/models/questionnaire.dart
- lib/models/questionnaire_store.dart
- lib/screens/home.dart
- lib/view_models/questionnaire_provider.dart
- lib/widgets/question_dialog/question_dialog.dart
- lib/widgets/question_dialog/question_list.dart
- lib/widgets/question_dialog/question_summary.dart
- lib/widgets/question_inputs/duration_input.dart
- lib/widgets/question_inputs/number_input.dart
- lib/widgets/question_inputs/question_input_widget.dart
- lib/widgets/question_inputs/string_input.dart
> Store and restore questionnaires

- lib/api/osm_element_query_api.dart
- lib/models/geometric_osm_element.dart
- lib/screens/home.dart
- lib/widgets/geometry_layer.dart
- pubspec.lock
- test/osm_to_geometry_test.dart
Todo:
-  Ring building works correctly, however the retrieved data is incomplete. It misses ways and nodes that are necessary to build the multipolygon because they lie outside of the queried bounding box.
Postpone:
> Visualize OSM element geometry

- .github/workflows/build_app.yml
- lib/screens/onboarding.dart
- lib/widgets/question_inputs/bool_input.dart
- lib/widgets/question_inputs/list_input.dart
Only trigger build workflow when a new tag is pushed, a release is triggered or workflow is triggered manually.
> Update build workflow

- lib/screens/home.dart
- lib/view_models/osm_elements_provider.dart
Add messages on StopArea tap in case of:
- Connection Timeout
- Unknown Error
- All Questions answered
> Add messages on StopArea tap

- assets/datasets/expression_schema.json
- assets/datasets/map_feature_collection.json
- assets/datasets/map_feature_collection_schema.json
- assets/datasets/question_catalog.json
- assets/datasets/question_catalog_schema.json
- docs/QUESTION_CATALOG.md
- lib/models/expression_handler.dart
- lib/models/map_feature.dart
- lib/models/question_catalog/answer_constructor.dart
- lib/models/question_catalog/answer_definition.dart
- lib/screens/home.dart
- lib/utils/geo_utils.dart
- lib/view_models/questionnaire_provider.dart
- lib/widgets/osm_element_layer/osm_element_layer.dart
- lib/widgets/osm_element_layer/osm_element_marker.dart
- test/answer_constructor_test.dart
Minor bugs:
- text overflow ellipsis sometimes swallows the last word completely (see https://github.com/flutter/flutter/issues/18761)
- temaki icons exceed the bounding box of the icon widget at the bottom (reason is currently unknown)
> Add expandable marker with details

- lib/commons/themes.dart
- lib/screens/settings.dart
- lib/widgets/home_sidebar.dart
- lib/widgets/map_overlay/compass_button.dart
- lib/widgets/map_overlay/loading_indicator.dart
- lib/widgets/map_overlay/location_button.dart
- lib/widgets/map_overlay/map_layer_switcher.dart
- lib/widgets/map_overlay/map_overlay.dart
- lib/widgets/map_overlay/zoom_button.dart
- lib/widgets/osm_element_layer/osm_element_layer.dart
- lib/widgets/osm_element_layer/osm_element_marker.dart
- lib/widgets/question_dialog/question_summary.dart
- lib/widgets/question_inputs/duration_input.dart
- lib/widgets/question_inputs/number_input.dart
- lib/widgets/question_inputs/string_input.dart
- lib/widgets/select_dialog.dart
* Rename parameter
* Remove obsolete parameter
* Streamline used theme colors
* Replace Login Button with FAB
* Rename Action Buttons for Select/Alert Dialog
> Switch to Material 3

- lib/widgets/home_sidebar.dart
Only noticeable problem in my emulator:
I would be okay with that.
> Simplify user profile header

- lib/api/osm_element_upload_api.dart
- lib/models/element_processing/element_filter.dart
- lib/models/element_processing/element_pool.dart
- lib/models/element_processing/element_processor.dart
- lib/models/element_processing/element_worker.dart
- lib/screens/home.dart
- lib/utils/service_worker.dart
- lib/view_models/osm_elements_provider.dart
- test/osm_to_geometry_test.dart
> Store all elements in single pool instead of a per stop area basis

- assets/datasets/question_catalog.json
- ios/Podfile.lock
> Improve speech output question

- assets/datasets/question_catalog.json
The added sentence was already part of the question about handrails, but not about elevator buttons.
> Copy extended `tactile_writing` description

- assets/datasets/question_catalog.json
> Fix typos and grammar mistakes in questions/descriptions

- .github/actions/environment_setup/action.yml
- .github/workflows/tests.yml
Re-add workflow working directory which was removed in https://github.com/OPENER-next/OpenStop/commit/198597b887ad3c0ddbd1f26b82a62354af77f26b
> Fix test workflow

- assets/datasets/question_catalog.json
This PR adds images to the wheelchair ramp question that were previously only used in the inititial existence question.
It also makes both wheelchair lift images show on all wheelchair lift questions, where previously only one image was shown on both questions.
> Fixes for images in wheelchair lift/wheelchair ramp questions

- assets/datasets/question_catalog.json
…regarding automatic opening
Refers to https://github.com/OPENER-next/OpenStop/pull/164#issuecomment-1517680060
> Differentiate between revovling doors and other types 

- assets/datasets/question_catalog.json
This PR adds a question that asks if `public_transport=platform`s are lit.
> Add lit question

- assets/datasets/question_catalog.json
This PR adds a question for `maxwidth:physical` on platforms.
> Add maxwidth:physical question

- assets/datasets/question_catalog.json
This PR adds two questions for professionals that asks for `ref:IFOPT` on `public_transport=platform`s and `public_transport=stop_area`s.
> Add DHID-question

- android/build.gradle
- lib/api/app_worker/stop_area_handler.dart
- lib/api/preferences_service.dart
- lib/models/geographic_geometries.dart
- lib/screens/home.dart
- lib/utils/map_utils.dart
- lib/view_models/home_view_model.dart
- lib/widgets/loading_area_layer/map_layer.dart
- lib/widgets/osm_element_layer/osm_element_layer.dart
- lib/widgets/stops_layer/points_layer.dart
- pubspec.lock
- pubspec.yaml
- test/osm_to_geometry_test.dart
- test/osm_upload_api_test.dart
- test/widget_test.dart
Requires flutter map upstream PR to be merged.
> Improve marker zoom

- assets/question_catalog/locales/en.arb
"Is this stop lighted at night" seems wrong, but I don't speak English as a first language.
I changed it to "Is this stop lit at night"
> Correct "lighted" to "lit"

- lib/commons/tile_layers.dart
- lib/screens/home.dart
- on devices with device pixel ratio <= 1 non retina tiles will be loaded
- on devices with device pixel ratio > 1 retina tiles will be loaded
> Base tile resolution on user's device pixel ratio

- lib/api/app_worker/stop_area_handler.dart
- lib/models/geographic_geometries.dart
- lib/models/stop_area_processing/stop_area.dart
- lib/utils/geo_utils.dart
- lib/utils/map_utils.dart
- lib/view_models/home_view_model.dart
- lib/widgets/loading_area_layer/map_layer.dart
- lib/widgets/stops_layer/points_layer.dart
- lib/widgets/stops_layer/stop_area_layer.dart
- pubspec.lock
- pubspec.yaml
> Fix marker layer rotation

- assets/question_catalog/definition.json
Exclude automatic doors in question about open state
> Update conditions for "open"-question

- .github/workflows/build_app.yml
- .github/workflows/code_validation.yml
- .github/workflows/json_validation.yml
- .github/workflows/tests.yml
This PR:
- updates the used GitHub actions to their latest version to get rid of all the warnings about deprecation,
- sets a specific python version (3.12) for JSON validation,
- sets if conditions to avoid running jobs twice unnecessarily
> Update GitHub Actions

- assets/question_catalog/definition.json
> Do not ask for "passenger_information_display" if "departures_board" is "realtime"

- android/app/build.gradle
- android/settings.gradle
- devtools_options.yaml
- ios/Runner/AppDelegate.swift
- lib/api/osm_authentication_api.dart
- lib/models/stop_area/stop_area.dart
- lib/widgets/geometry_layer.dart
- pubspec.lock
- pubspec.yaml
- Update Flutter Map version to 7 (from 6)
- Update Geolocator version to 13 (from 11)
- Update Kotlin Plugin version to 1.9.10 (from 1.7.10)
- Remove dependency override for geolocator_android
- Set minSdkVersion to 24 (from 23)
- Fix wrong type in login procedure which prevented successful login
- Fix linter warning
> Update dependencies and fixes

- ios/Podfile.lock
- lib/api/app_worker/stop_area_handler.dart
- lib/screens/onboarding.dart
- lib/widgets/custom_list_tile.dart
- lib/widgets/geometry_layer.dart
- lib/widgets/home_sidebar/login_info_header.dart
- lib/widgets/home_sidebar/user_account_header.dart
- lib/widgets/loading_area_layer/ripple_indicator.dart
- lib/widgets/map_overlay/credit_text.dart
- lib/widgets/map_overlay/zoom_button.dart
- lib/widgets/osm_element_layer/osm_element_layer.dart
- lib/widgets/osm_element_layer/osm_element_marker.dart
- lib/widgets/question_dialog/question_navigation_bar.dart
- lib/widgets/question_dialog/question_text_header.dart
- lib/widgets/question_inputs/bool_input.dart
- lib/widgets/question_inputs/duration_input.dart
- pubspec.lock
- pubspec.yaml
- test/osm_upload_api_test.dart
- test/widget_test.dart
This PR updates Flutter to its newest stable version.
> Adaption to new Flutter  version

- lib/screens/onboarding.dart
- lib/widgets/home_sidebar/login_info_header.dart
- lib/widgets/question_dialog/question_navigation_bar.dart
- pubspec.lock
- pubspec.yaml
Due to an upstream fix some lines of code could be removed https://github.com/flutter/flutter/pull/162880
> Upgrade to Flutter 3.29.1

- .github/workflows/tests.yml
See https://github.com/openstreetmap/openstreetmap-website/commit/d52c7943f24aae4ede55f1ef055af415dcf3da59
> Fix OSM docker setup
